export enum EnvConfig {
  PRO_NAME = 'PRO_NAME',
  ENV = 'ENV',
  PORT = 'PORT',
  HOST = 'HOST',
  DB_TYPE = 'DB_TYPE',
  DB_DATABASE = 'DB_DATABASE',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  JWT_SECRET = 'JWT_SECRET'
}
